root: true

env:
  es6: true
  node: true

extends:
  eslint

rules:
  indent: [2, 2, { SwitchCase: 1 }]
  no-underscore-dangle: 0
  no-use-before-define: [2, { functions: false }]
  quotes: [2, single]
