language: node_js

node_js:
  - "6"
  - "5"
  - "4"

notifications:
  email: false

cache:
  directories:
    - webrtc

before_cache:
  - rm -rf webrtc/src/out

env:
  global:
    - CASHER_TIME_OUT=3600

install:
  - npm install --ignore-scripts
  - ./node_modules/.bin/jake `pwd`/webrtc/src

script:
  - npm run lint
